version: "3.9"

services:
  nginx:
    image: nginx:latest
    container_name: medbook-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "3000:80"
    depends_on:
      - medbook-userservice
      - medbook-bookingservice
    networks:
      - medbook-userservice-backend
      - medbook-bookingservice-backend
  medbook-userservice:
    image: ghcr.io/pasobeso/medbook-userservice:latest
    container_name: medbook-userservice
    restart: unless-stopped
    env_file:
      - medbook-userservice.env
    depends_on:
      - medbook-userservice-db
    networks:
      - medbook-userservice-backend

  medbook-userservice-db:
    image: bitnami/postgresql:latest
    container_name: medbook-userservice-db
    restart: unless-stopped
    env_file: medbook-userservice.env
    volumes:
      - medbook_userservice_data:/bitnami/postgresql
    networks:
      - medbook-userservice-backend
  medbook-bookingservice:
    image: ghcr.io/pasobeso/medbook-bookingservice:latest
    container_name: medbook-bookingservice
    restart: unless-stopped
    env_file:
      - medbook-bookingservice.env
    depends_on:
      - medbook-bookingservice-db
    networks:
      - medbook-bookingservice-backend

  medbook-bookingservice-db:
    image: bitnami/postgresql:latest
    container_name: medbook-bookingservice-db
    restart: unless-stopped
    env_file: medbook-bookingservice.env
    volumes:
      - medbook_bookingservice_data:/bitnami/postgresql
    networks:
      - medbook-bookingservice-backend

volumes:
  medbook_bookingservice_data:
  medbook_userservice_data:

networks:
  medbook-bookingservice-backend:
    driver: bridge
  medbook-userservice-backend:
    driver: bridge
