services:
  # NGINX gateway
  medbook-nginx-dev:
    image: nginx:latest
    container_name: medbook-nginx-dev
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "3000:80"
    restart: unless-stopped
    depends_on:
      - medbook-userservice-dev
      - medbook-bookingservice-dev
      - medbook-inventoryservice-dev
      - medbook-deliveryservice-dev
      - medbook-orderservice-dev
    networks:
      - api-backend

  # CloudBeaver
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    restart: unless-stopped
    ports:
      - "8978:8978"
    volumes:
      - cb_workspace:/opt/cloudbeaver/workspace
    environment:
      # Optional: set server URL if using reverse proxy or custom domain
      CB_SERVER_URL: "http://localhost:8978"
    networks:
      - api-backend

  # RMQ
  rmq:
    image: rabbitmq:management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia
    networks:
      - api-backend

  # UserService
  medbook-userservice-dev:
    image: ghcr.io/pasobeso/medbook-userservice:latest
    container_name: medbook-userservice-dev
    restart: unless-stopped
    env_file:
      - medbook-userservice-dev.env
      - medbook-rmq-dev.env
      - medbook-authtoken-dev.env
      - medbook-stage-dev.env
      - medbook-frontend-url.env
    depends_on:
      - medbook-userservice-db-dev
    networks:
      - api-backend
  medbook-userservice-db-dev:
    image: bitnami/postgresql:latest
    container_name: medbook-userservice-db-dev
    restart: unless-stopped
    env_file: medbook-userservice-dev.env
    volumes:
      - medbook_userservice_data_dev:/bitnami/postgresql
    networks:
      - api-backend

  # BookingService
  medbook-bookingservice-dev:
    image: ghcr.io/pasobeso/medbook-bookingservice:latest
    container_name: medbook-bookingservice-dev
    restart: unless-stopped
    env_file:
      - medbook-bookingservice-dev.env
      - medbook-rmq-dev.env
      - medbook-authtoken-dev.env
      - medbook-stage-dev.env
      - medbook-frontend-url.env
    depends_on:
      - medbook-bookingservice-db-dev
    networks:
      - api-backend
  medbook-bookingservice-db-dev:
    image: bitnami/postgresql:latest
    container_name: medbook-bookingservice-db-dev
    restart: unless-stopped
    env_file: medbook-bookingservice-dev.env
    volumes:
      - medbook_bookingservice_data_dev:/bitnami/postgresql
    networks:
      - api-backend

  # InventoryService
  medbook-inventoryservice-dev:
    image: ghcr.io/pasobeso/medbook-inventoryservice:latest
    container_name: medbook-inventoryservice-dev
    restart: unless-stopped
    env_file:
      - medbook-inventoryservice-dev.env
      - medbook-rmq-dev.env
      - medbook-authtoken-dev.env
      - medbook-stage-dev.env
      - medbook-frontend-url.env
    depends_on:
      - medbook-inventoryservice-db-dev
    networks:
      - api-backend
  medbook-inventoryservice-db-dev:
    image: bitnami/postgresql:latest
    container_name: medbook-inventoryservice-db-dev
    restart: unless-stopped
    env_file: medbook-inventoryservice-dev.env
    volumes:
      - medbook_inventoryservice_data_dev:/bitnami/postgresql
    networks:
      - api-backend

  # DeliveryService
  medbook-deliveryservice-dev:
    image: ghcr.io/pasobeso/medbook-deliveryservice:latest
    container_name: medbook-deliveryservice-dev
    restart: unless-stopped
    env_file:
      - medbook-deliveryservice-dev.env
      - medbook-rmq-dev.env
      - medbook-authtoken-dev.env
      - medbook-stage-dev.env
      - medbook-frontend-url.env
    depends_on:
      - medbook-deliveryservice-db-dev
    networks:
      - api-backend
  medbook-deliveryservice-db-dev:
    image: bitnami/postgresql:latest
    container_name: medbook-deliveryservice-db-dev
    restart: unless-stopped
    env_file: medbook-deliveryservice-dev.env
    volumes:
      - medbook_deliveryservice_data_dev:/bitnami/postgresql
    networks:
      - api-backend

  # OrderService
  medbook-orderservice-dev:
    image: ghcr.io/pasobeso/medbook-orderservice:latest
    container_name: medbook-orderservice-dev
    restart: unless-stopped
    env_file:
      - medbook-orderservice-dev.env
      - medbook-rmq-dev.env
      - medbook-authtoken-dev.env
      - medbook-stage-dev.env
      - medbook-frontend-url.env
    depends_on:
      - medbook-orderservice-db-dev
    networks:
      - api-backend
  medbook-orderservice-db-dev:
    image: bitnami/postgresql:latest
    container_name: medbook-orderservice-db-dev
    restart: unless-stopped
    env_file: medbook-orderservice-dev.env
    volumes:
      - medbook_orderservice_data_dev:/bitnami/postgresql
    networks:
      - api-backend

volumes:
  medbook_bookingservice_data_dev:
  medbook_userservice_data_dev:
  medbook_inventoryservice_data_dev:
  medbook_deliveryservice_data_dev:
  medbook_orderservice_data_dev:
  rabbitmq_data:
  cb_workspace:

networks:
  api-backend:
    driver: bridge
